# Generated by Django 4.1.7 on 2023-03-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(default="0", max_length=200, unique=True)),
                ("year", models.IntegerField(default="0", null=True)),
                (
                    "owner_name",
                    models.CharField(default="0", max_length=200, null=True),
                ),
                ("employees", models.IntegerField(default="0", null=True)),
                ("country", models.CharField(default="0", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("description", models.CharField(default="", max_length=500)),
                ("review", models.CharField(default="", max_length=500)),
                ("price", models.IntegerField(default="0")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="lab1.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_customer", models.CharField(max_length=200)),
                ("year_of_birth", models.IntegerField(default="0")),
                ("address", models.CharField(default="0", max_length=500)),
                ("gender", models.CharField(default="0", max_length=100)),
                ("phone", models.IntegerField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="CarsSold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default="2000-12-20")),
                ("amount", models.IntegerField(default="0")),
                (
                    "cars_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars_id",
                        to="lab1.cars",
                    ),
                ),
                (
                    "customers_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers_id",
                        to="lab1.customers",
                    ),
                ),
            ],
        ),
    ]
